name: Build and Export Workflow

on:
  push:
    branches:
      - main  # or your preferred branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npm run build  # Replace with your build command/script

      - name: Create ZIP file
        run: zip -r my_app.zip dist/*  # Replace 'my_app.zip' and 'dist/*' as needed

      - name: Upload ZIP to subgroup
        uses: actions/upload-artifact@v2
        with:
          name: my_app_artifact
          path: my_app.zip  # Adjust this if you changed the ZIP filename

  export:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ZIP artifact
        uses: actions/download-artifact@v2
        with:
          name: my_app_artifact  # Use the same name as defined in the 'upload-artifact' step

      - name: Export to subgroup
        run: |
          # Example command to export the ZIP file to a subgroup repository
          # Replace placeholders with actual values
          # You might need to authenticate and use appropriate Git commands
          git clone https://github.com/yourusername/subgroup-repo.git
          cp my_app.zip subgroup-repo/
          cd subgroup-repo
          git add my_app.zip
          git commit -m "Add latest build"
          git push origin main

# Note: This is a simplified example and might require adjustments to fit your exact setup.
